In [ ]:
import tensorflow as tf
from tensorflow.keras import models, layers, losses
from google.colab import drive
import matplotlib.pyplot as plt
import os
import cv2
import pandas as pd
import numpy as np
import random
import math
drive.mount('/content/drive')
os.chdir('/content/drive/Shareddrives/ML_final_team01')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
male_train_csv = pd.read_csv("male_train.csv")
directory = 'male-crop-train-png'
file_dir = os.listdir(directory)
random.shuffle(file_dir)
file_dir = file_dir[:2000]
y_train = np.zeros((len(file_dir), 4))
X_train = np.zeros((len(file_dir), 216, 334, 3))
for p in range(len(file_dir)):
    img = cv2.imread(directory+"/"+file_dir[p])
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255
    X_train[p] = np.reshape(img, (216, 334, 3))
    row = male_train_csv.loc[male_train_csv['filename'] == 'cv-other-train/'+file_dir[p][:-3]+'mp3']
    if row['age'].values[0] == 'teens' or row['age'].values[0] == 'twenties':
        y_train[p][0] = 1
    elif row['age'].values[0] == 'thirties' or row['age'].values[0] == 'fourties':
        y_train[p][1] = 1
    elif row['age'].values[0] == 'fifties' or row['age'].values[0] == 'sixties':
        y_train[p][2] = 1
    elif row['age'].values[0] == 'seventies' or row['age'].values[0] == 'eighties' or row['age'].values[0] == 'nineties':
        y_train[p][3] = 1

In [ ]:

'''
# count the number of each labels
count_label = [0, 0, 0, 0, 0, 0, 0]
index_memo = [[], [], [],[] , [], [], []]
for i in range(len(file_dir)):
    #print(file_dir[i])
    row = male_train_csv.loc[male_train_csv['filename'] == 'cv-other-train/'+file_dir[i][:-3]+'mp3']
    # print(row['age'].values[0])
    if row['age'].values[0] == 'teens':
        count_label[0] += 1
        index_memo[0].append(i)
    elif row['age'].values[0] == 'twenties':
        count_label[1] += 1
        index_memo[1].append(i)
    elif row['age'].values[0] == 'thirties':
        count_label[2] += 1
        index_memo[2].append(i)
    elif row['age'].values[0] == 'fourties':
        count_label[3] += 1
        index_memo[3].append(i)
    elif row['age'].values[0] == 'fifties':
        count_label[4] += 1
        index_memo[4].append(i)
    elif row['age'].values[0] == 'sixties':
        count_label[5] += 1
        index_memo[5].append(i)
    elif row['age'].values[0] == 'seventies' or row['age'].values[0] == 'eighties' or row['age'].values[0] == 'nineties':
        count_label[6] += 1
        index_memo[6].append(i)
print(count_label)
'''

"\n# count the number of each labels\ncount_label = [0, 0, 0, 0, 0, 0, 0]\nindex_memo = [[], [], [],[] , [], [], []]\nfor i in range(len(file_dir)):\n    #print(file_dir[i])\n    row = male_train_csv.loc[male_train_csv['filename'] == 'cv-other-train/'+file_dir[i][:-3]+'mp3']\n    # print(row['age'].values[0])\n    if row['age'].values[0] == 'teens':\n        count_label[0] += 1\n        index_memo[0].append(i)\n    elif row['age'].values[0] == 'twenties':\n        count_label[1] += 1\n        index_memo[1].append(i)\n    elif row['age'].values[0] == 'thirties':\n        count_label[2] += 1\n        index_memo[2].append(i)\n    elif row['age'].values[0] == 'fourties':\n        count_label[3] += 1\n        index_memo[3].append(i)\n    elif row['age'].values[0] == 'fifties':\n        count_label[4] += 1\n        index_memo[4].append(i)\n    elif row['age'].values[0] == 'sixties':\n        count_label[5] += 1\n        index_memo[5].append(i)\n    elif row['age'].values[0] == 'seventies' or

In [ ]:
'''
# convert label to one-hot encoded
y_train = np.zeros((max(count_label) * 7, 7))
# balance the data of different labels.
X_train = np.array([])
X_train = np.zeros((max(count_label) * 7, 216, 334, 3))
duplicate_time = [math.floor(max(count_label)/ i) for i in count_label ]
print(duplicate_time)
file_count = 0
p = 0
while p < max(count_label) * 7 and file_count < 1000:
    print(file_count)
    img = cv2.imread(directory+"/"+file_dir[file_count])
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255
    if file_count in index_memo[0]:
        print('in [0]')
        file_count = file_count + 1
        for j in range(duplicate_time[0]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][0] = 1
            p = p + 1
    elif file_count in index_memo[1]:
        print('in [1]')
        file_count = file_count + 1
        for j in range(duplicate_time[1]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][1] = 1
            p = p + 1
    elif file_count in index_memo[2]:
        print('in [2]')
        file_count = file_count + 1
        for j in range(duplicate_time[2]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][2] = 1
            p = p + 1
    elif file_count in index_memo[3]:
        print('in [3]')
        file_count = file_count + 1
        for j in range(duplicate_time[3]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][3] = 1
            p = p + 1
    elif file_count in index_memo[4]:
        print('in [4]')
        file_count = file_count + 1
        for j in range(duplicate_time[4]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][4] = 1            
            p = p + 1
    elif file_count in index_memo[5]:
        print('in [5]')
        file_count = file_count + 1
        for j in range(duplicate_time[5]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][5] = 1
            p = p + 1
    elif file_count in index_memo[6]:
        print('in [6]')
        file_count = file_count + 1
        for j in range(duplicate_time[6]):
            X_train[p] = np.reshape(img, (216, 334, 3))
            y_train[p][6] = 1
            p = p + 1
'''

'\n# convert label to one-hot encoded\ny_train = np.zeros((max(count_label) * 7, 7))\n# balance the data of different labels.\nX_train = np.array([])\nX_train = np.zeros((max(count_label) * 7, 216, 334, 3))\nduplicate_time = [math.floor(max(count_label)/ i) for i in count_label ]\nprint(duplicate_time)\nfile_count = 0\np = 0\nwhile p < max(count_label) * 7 and file_count < 1000:\n    print(file_count)\n    img = cv2.imread(directory+"/"+file_dir[file_count])\n    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n    img = img / 255\n    if file_count in index_memo[0]:\n        print(\'in [0]\')\n        file_count = file_count + 1\n        for j in range(duplicate_time[0]):\n            X_train[p] = np.reshape(img, (216, 334, 3))\n            y_train[p][0] = 1\n            p = p + 1\n    elif file_count in index_memo[1]:\n        print(\'in [1]\')\n        file_count = file_count + 1\n        for j in range(duplicate_time[1]):\n            X_train[p] = np.reshape(img, (216, 334, 3))\n       

In [ ]:

# get validation data
directory = 'male-crop-test-png'
file_dir = os.listdir(directory)
random.shuffle(file_dir)
file_dir = file_dir[:300]
#print(file_dir)
X_test = np.array([])
X_test = np.zeros((len(file_dir), 216, 334, 3))
for p in range(len(file_dir)):
    img = cv2.imread(directory+"/"+file_dir[p])
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255
    X_test[p] = np.reshape(img, (216, 334, 3))


In [ ]:
male_test_csv = pd.read_csv("male_test.csv")
# convert label to one-hot encoded
y_test = np.zeros((len(file_dir), 4))
for i in range(len(file_dir)):
    #print(file_dir[i])
    row = male_test_csv.loc[male_test_csv['filename'] == 'cv-other-test/'+file_dir[i][:-3]+'mp3']
    # print(row['age'].values[0])
    if row['age'].values[0] == 'teens' or row['age'].values[0] == 'twenties':
        y_test[i][0] = 1
    elif row['age'].values[0] == 'thirties' or row['age'].values[0] == 'fourties':
        y_test[i][1] = 1
    elif row['age'].values[0] == 'fifties' or row['age'].values[0] == 'sixties':
        y_test[i][2] = 1
    elif row['age'].values[0] == 'seventies' or row['age'].values[0] == 'eighties' or row['age'].values[0] == 'nineties':
        y_test[i][3] = 1
print(y_test)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [ ]:
model = models.Sequential()
model.add(layers.RandomFlip("horizontal"))
model.add(layers.Conv2D(32, (4, 4), strides = 1, activation = 'relu', input_shape = (216, 334, 3)))
model.add(layers.MaxPooling2D((4, 4), strides = 2))
model.add(layers.Conv2D(32, (4, 4), activation='relu', strides = 2))
model.add(layers.MaxPooling2D((4, 4), strides = 2))
model.add(layers.Conv2D(64, (4, 4), activation='relu', strides = 2))
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(4, activation='softmax'))
#model.summary()
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=[tf.keras.metrics.CategoricalAccuracy()])
History = model.fit(X_train, y_train, batch_size = 50, epochs = 13, validation_data = (X_test, y_test))

Epoch 1/15
40/40 [==============================] - 13s 124ms/step - loss: 1.1316 - categorical_accuracy: 0.4220 - val_loss: 1.0552 - val_categorical_accuracy: 0.4000
Epoch 2/15
40/40 [==============================] - 4s 110ms/step - loss: 1.0839 - categorical_accuracy: 0.4275 - val_loss: 1.0819 - val_categorical_accuracy: 0.4000
Epoch 3/15
40/40 [==============================] - 4s 112ms/step - loss: 1.0863 - categorical_accuracy: 0.4285 - val_loss: 1.0494 - val_categorical_accuracy: 0.4833
Epoch 4/15
40/40 [==============================] - 5s 127ms/step - loss: 1.0764 - categorical_accuracy: 0.4475 - val_loss: 1.0433 - val_categorical_accuracy: 0.4700
Epoch 5/15
40/40 [==============================] - 4s 112ms/step - loss: 1.0698 - categorical_accuracy: 0.4735 - val_loss: 1.0351 - val_categorical_accuracy: 0.4733
Epoch 6/15
40/40 [==============================] - 5s 113ms/step - loss: 1.0498 - categorical_accuracy: 0.4695 - val_loss: 1.0196 - val_categorical_accuracy: 0.4500
Epo

In [ ]:
# model.save('male-age-pred')
pred = model.predict_proba(X_test[2].reshape(1, 216, 334, 3))
pred

NameError: ignored

In [ ]:
import numpy as np
age = ['0~30 years old', '30~50 years old', '50~70 years old', 'older than seventies']
outcome = (-pred[0]).argsort()[:2]
print(round(pred[0][outcome[0]] * 100, 1), "% from", age[outcome[0]])
print(round(pred[0][outcome[1]] * 100, 1), "% from", age[outcome[1]])

81.4 % from 0~30 years old
16.8 % from 30~50 years old
